ToolsSchool/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace ToolsSchool.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View("../About/Index");
        }
    }
}

ToolsSchool/Controllers/HelpController.cs
using Microsoft.AspNetCore.Mvc;

namespace ToolsSchool.Controllers
{
    public class HelpController : Controller
    {
        public IActionResult Index()
        {
            return View("../Help/Index");
        }
    }
}

ToolsSchool/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ToolsSchool.Models;

namespace ToolsSchool.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToolsSchool/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToolsSchool.DB;
using ToolsSchool.Entities;

namespace ToolsSchool.Controllers
{
    public class ProductsController : Controller
    {
        private readonly SchoolDB _context;

        public ProductsController(SchoolDB context)
        {
            _context = context;
        }

        // GET: Products/Index
        public async Task<IActionResult> Index(string category = null, string search = null,
                                               int page = 1, int pageSize = 12)
        {
            IQueryable<Product> query = _context.Products
                .Where(p => 
                           (!p.ExpiryDate.HasValue || p.ExpiryDate.Value > System.DateTime.Now))
                .OrderByDescending(p => p.CreatedDate);

            // فیلتر بر اساس دسته‌بندی
            if (!string.IsNullOrEmpty(category))
            {
                query = query.Where(p => p.Category == category);
                ViewBag.SelectedCategory = category;
            }

            // جستجو
            if (!string.IsNullOrEmpty(search))
            {
                query = query.Where(p => p.ProductName.Contains(search) ||
                                        p.Description.Contains(search));
                ViewBag.SearchQuery = search;
            }

            // محاسبه اطلاعات صفحه‌بندی
            var totalItems = await query.CountAsync();
            var totalPages = (int)System.Math.Ceiling((double)totalItems / pageSize);

            // گرفتن آیتم‌های صفحه جاری
            var products = await query
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            // ارسال اطلاعات به View
            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = totalPages;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalItems = totalItems;

            // گرفتن لیست دسته‌بندی‌ها برای فیلتر
            ViewBag.Categories = await _context.Products
                .Select(p => p.Category)
                .Distinct()
                .ToListAsync();

            return View(products);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var product = await _context.Products
                .FirstOrDefaultAsync(p => p.Id == id );

            if (product == null)
            {
                return NotFound();
            }

            // افزایش تعداد بازدید
            product.ViewCount++;
            _context.Update(product);
            await _context.SaveChangesAsync();

            // گرفتن محصولات مرتبط
            var relatedProducts = await _context.Products
                .Where(p => p.Category == product.Category &&
                           p.Id != product.Id )
                .OrderByDescending(p => p.CreatedDate)
                .Take(4)
                .ToListAsync();

            ViewBag.RelatedProducts = relatedProducts;

            return View(product);
        }

        // GET: Products/ByCategory/{category}
        public async Task<IActionResult> ByCategory(string category, int page = 1)
        {
            if (string.IsNullOrEmpty(category))
            {
                return RedirectToAction("Index");
            }

            var products = await _context.Products
                .Where(p => p.Category == category &&
                           (!p.ExpiryDate.HasValue || p.ExpiryDate.Value > System.DateTime.Now))
                .OrderByDescending(p => p.CreatedDate)
                .ToListAsync();

            ViewBag.CategoryName = category;
            ViewBag.CurrentPage = page;

            return View("Index", products);
        }

        // GET: Products/Search
        public async Task<IActionResult> Search(string query, int page = 1)
        {
            if (string.IsNullOrEmpty(query))
            {
                return RedirectToAction("Index");
            }

            var products = await _context.Products
                .Where(p => (p.ProductName.Contains(query) ||
                            p.Description.Contains(query)) &&
                           (!p.ExpiryDate.HasValue || p.ExpiryDate.Value > System.DateTime.Now))
                .OrderByDescending(p => p.CreatedDate)
                .ToListAsync();

            ViewBag.SearchQuery = query;
            ViewBag.CurrentPage = page;

            return View("Index", products);
        }
    }
}

ToolsSchool/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "وسایل مدرسه";
}
<a class="z_index" href="#">
    <img style="border-radius:8px" width="1500" height="250" src="~/media/ok_3_qij8.jpg" />
    <style>
        .img-text {
            position: absolute;
            top: 50%;
            right: 68%;
            transform: translate(50%, -50%);
            color: black;
            font-size: 20px;
            font-weight: bold;
            padding: 8px 12px;
            border-radius: 8px;
        }
    </style>
    <div class="img-text">
        به سایت همکلاسی خوش آمدید.....
        وسایل دست دوم خودتان را اینجا بفروشید
    </div>
</a>
<br />
<br />
<div class="d-flex justify-content-between">
    <div class="icon-row my-0">
        <i class="bi bi-key"></i>
        <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-key" viewBox="0 0 20 20">
            <path d="M0 8a4 4 0 0 1 7.465-2H14a.5.5 0 0 1 .354.146l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0L13 9.207l-.646.647a.5.5 0 0 1-.708 0L11 9.207l-.646.647a.5.5 0 0 1-.708 0L9 9.207l-.646.647A.5.5 0 0 1 8 10h-.535A4 4 0 0 1 0 8m4-3a3 3 0 1 0 2.712 4.285A.5.5 0 0 1 7.163 9h.63l.853-.854a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.793-.793-1-1h-6.63a.5.5 0 0 1-.451-.285A3 3 0 0 0 4 5" />
            <path d="M4 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
            <p style="color:black">خرید امن</p>
        </svg>
    </div>
    <div class="icon-row text- my-0">
        <i class="bi bi-backpack3"></i>
        <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-backpack3" viewBox="0 0 20 20">
            <path d="M4.04 7.43a4 4 0 0 1 7.92 0 .5.5 0 1 1-.99.14 3 3 0 0 0-5.94 0 .5.5 0 1 1-.99-.14M4 9.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1-.5-.5zm1 .5v3h6v-3h-1v.5a.5.5 0 0 1-1 0V10z" />
            <path d="M6 2.341V2a2 2 0 1 1 4 0v.341c.465.165.904.385 1.308.653l.416-1.247a1 1 0 0 1 1.748-.284l.77 1.027a1 1 0 0 1 .15.917l-.803 2.407C13.854 6.49 14 7.229 14 8v5.5a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 2 13.5V8c0-.771.146-1.509.41-2.186l-.802-2.407a1 1 0 0 1 .15-.917l.77-1.027a1 1 0 0 1 1.748.284l.416 1.247A6 6 0 0 1 6 2.34ZM7 2v.083a6 6 0 0 1 2 0V2a1 1 0 1 0-2 0m5.941 2.595.502-1.505-.77-1.027-.532 1.595q.447.427.8.937M3.86 3.658l-.532-1.595-.77 1.027.502 1.505q.352-.51.8-.937M8 3a5 5 0 0 0-5 5v5.5A1.5 1.5 0 0 0 4.5 15h7a1.5 1.5 0 0 0 1.5-1.5V8a5 5 0 0 0-5-5" />
            <p style="color:black">وسایل مدرسه</p>
        </svg>
    </div>
    <div class="icon-row text- my-0">
        <i class="bi bi-plus-circle"></i>
        <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 20 20">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
            <p style="color:black">ثبت آگهی رایگان</p>
        </svg>
    </div>
    <div class="icon-row text- my-0">
        <i class="bi bi-fast-forward-circle"></i>
        <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-fast-forward-circle" viewBox="0 0 20 20">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
            <path d="M4.271 5.055a.5.5 0 0 1 .52.038L8 7.386V5.5a.5.5 0 0 1 .79-.407l3.5 2.5a.5.5 0 0 1 0 .814l-3.5 2.5A.5.5 0 0 1 8 10.5V8.614l-3.21 2.293A.5.5 0 0 1 4 10.5v-5a.5.5 0 0 1 .271-.445" />
            <p style="color:black">ساده و سریع</p>
        </svg>
    </div>
</div>
<hr style="border: none; height: 2px; background-color: #808080;" />

<h2 style="text-align:center;color:black; top:63%">
   محصولات پیش فرض
</h2>
<div class="d-flex justify-content-between">

    <div class="p-2 m-2" style="border:solid;border-color:gray;border-radius:6px;">

        <img width="300" height="150" src="~/media/photo_2024-09-07_01-26-58-540x540.jpg" alt="#" class="img-fluid">
        <h3>
            <a style="color:purple;top:20%">
                ست لوازم تحریر
            </a>
        </h3>
        <p>قیمت:100,000</p>
        <p>کارکرد: نو</p>
    </div>
    <div class="p-2 m-2" style="border:solid;border-color:gray;border-radius:6px;">

        <img width="300" height="150" src="~/media/katoni8-3~2.jpg" alt="#" class="img-fluid">
        <h3>
            <a style="color:purple;top:20%">
                کتونی
            </a>
        </h3>

        <p>قیمت:500,000</p>
        <p>کارکرد: نو</p>
    </div>
    <div class="p-2 m-2" style="border:solid;border-color:gray;border-radius:6px;">

        <img width="300" height="150" src="~/media/کوله-پشتی-بچه-گانه-چند-جیب-در-۴-رنگ-با-پیکسل-و-آویز-رنگی-مشکی-600x600.jpg" alt="#" class="img-fluid">
        <h3>
            <a style="color:purple;top:20%">
                کوله پشتی
            </a>
        </h3>
        <p>قیمت:300,000</p>
        <p>کارکرد: در حد نو</p>
    </div>
</div>
<div class="d-flex justify-content-between">
    <div class="p-2 m-2" style="border:solid;border-color:gray;border-radius:6px;">

        <img width="300" height="150" src="~/media/5fa3a7544b8fb.jpg" alt="#" class="img-fluid">
        <h3>
            <a style="color:purple;top:20%">
                کتاب
            </a>
        </h3>
        <p>قیمت:200,000</p>
        <p>کارکرد: نو</p>
    </div>

    <div class="p-2 m-2" style="border:solid;border-color:gray;border-radius:6px;">
        <img width="300" height="150" src="~/media/download-2.jpg" alt="#" class="img-fluid">
        <h3>
            <a style="color:purple;top:20%">
                لباس مدرسه
            </a>
        </h3>
        <p>قیمت:1,000,000</p>
        <p>کارکرد: در حد نو</p>
    </div>
    <div class="p-2 m-2" style="border:solid;border-color:gray;border-radius:6px;">
        <img width="300" height="150" src="~/media/ساعت-scaled.jpg" alt="#" class="img-fluid">
        <h3>
            <a style="color:purple;top:20%">
                اکسسوری مدرسه
            </a>
        </h3>
        <p>قیمت:50,000</p>
        <p>کارکرد: نو</p>
    </div>
</div>
<br />
<a asp-controller="Products" asp-action="Index"
   style="text-decoration:none; color:black;
          display:flex; align-items:center; justify-content:center; gap:8px;">
    <p style="color:black; font-size:20px;">محصولات بیشتر</p>
    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30"
         fill="currentColor" viewBox="0 0 15 15">
        <path fill-rule="evenodd"
              d="M9.224 1.553a.5.5 0 0 1 .223.67L6.56 8l2.888 5.776a.5.5 0 1 1-.894.448l-3-6a.5.5 0 0 1 0-.448l3-6a.5.5 0 0 1 .67-.223" />
    </svg>
</a>
<h4 style="text-align:center;color:dimgrey">محصولات واقعی را اینجا ببینید</h4>
<hr style="border: none; height: 2px; background-color: #808080;" />
<ul style="list-style:none; padding:0; margin:0;">
    <li style="margin:15px 0;">
        <a asp-controller="About" asp-action="Index"
           style="text-decoration:none; color:black;
                  display:flex; align-items:center; justify-content:center; gap:10px;">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25"
                 fill="currentColor" viewBox="0 0 16 16">
                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z" />
            </svg>
            <span style="font-size:20px;">درباره ما</span>
        </a>
    </li>
    <li style="margin:15px 0;">
        <a asp-controller="Help" asp-action="Index"
           style="text-decoration:none; color:black;
                  display:flex; align-items:center; justify-content:center; gap:10px;">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25"
                 fill="currentColor" viewBox="0 0 16 16">
                <path d="M5 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0m4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0m3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2" />
                <path d="m2.165 15.803.02-.004c1.83-.363 2.948-.842 3.468-1.105A9 9 0 0 0 8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6a10.4 10.4 0 0 1-.524 2.318l-.003.011a11 11 0 0 1-.244.637c-.079.186.074.394.273.362a22 22 0 0 0 .693-.125m.8-3.108a1 1 0 0 0-.287-.801C1.618 10.83 1 9.468 1 8c0-3.192 3.004-6 7-6s7 2.808 7 6-3.004 6-7 6a8 8 0 0 1-2.088-.272 1 1 0 0 0-.711.074c-.387.196-1.24.57-2.634.893a11 11 0 0 0 .398-2" />
            </svg>
            <span style="font-size:20px;">تماس با ما</span>
        </a>
    </li>

</ul>